# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-05 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_authenticator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('item_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('recommended_items', models.CharField(max_length=300)),
            ],
        ),
    ]
